---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)

library(tidyverse)
library(sendmailR)
library(dotenv)
library(REDCapR)
library(lubridate)
library(kableExtra)

# set the timezone
Sys.setenv(TZ = Sys.getenv("TIME_ZONE"))

project_start_date <- ymd("2020-04-08")
current_date <- Sys.Date() - 1
```

### Covid19 Swab Results by agency for `r project_start_date` to `r current_date`
Since we do not specifically track ‘No-Show’ appointments for this study we are operating under the assumption that if the appointment occurred and 48 hours elapsed without a test result being entered then the subject did not show up for their appointment and thus had no sample collected.
```{r}
# read appointment data betewwen 2020-04-08 and current_date 
records <- redcap_read_oneshot(redcap_uri = 'https://redcap.ctsi.ufl.edu/redcap/api/',
                               token = Sys.getenv("FR_API_TOKEN"),
                               raw_or_label = "label")$data %>% 
  mutate(test_date_and_time = as_date(test_date_and_time),
         days_since_appt = current_date - test_date_and_time) %>% 
  filter(between(test_date_and_time, project_start_date, current_date))  
  
records <- records %>%
  mutate(
    q_agency = str_to_title(
      case_when(is.na(q_agency) ~ "Unknown Agency",
                TRUE ~ q_agency)),
    covid_19_swab_result = case_when(
      days_since_appt > 2 & is.na(covid_19_swab_result) ~ "No Show",
      days_since_appt <= 2 & is.na(covid_19_swab_result) ~ "Waiting for Results",
      TRUE ~ covid_19_swab_result)) %>%
  select("Agency" = q_agency, covid_19_swab_result)

appt_by_agency <- records %>% 
  count(Agency, covid_19_swab_result) %>%  
  group_by(Agency) %>% 
  mutate(perc = round(n/sum(n),2)*100,
         Total = sum(n),
         n = paste0(n, " (", perc,"%)")) %>% 
  select(-perc) %>% 
  ungroup() %>% 
  pivot_wider(names_from = covid_19_swab_result, values_from = n) %>% 
  mutate_all(replace_na, 0) %>% 
  select(Agency, Negative, `No Show`, `Waiting for Results`, Positive, Total)

kable(appt_by_agency) %>% 
  kable_styling("striped", full_width = F)
```
